## First Part

In [3]:
import numpy as np
print("ready")

ready


In [4]:
np.random.seed(1)

categories = ["Food", "Electronics", "Clothing", "Furniture"]
day_numbers = np.arange(1, 11)

daily_sales = np.random.randint(8000, 65000, size=(10, 4))
units_sold = np.random.randint(15, 350, size=(10, 4))

print(daily_sales)

print()

print(units_sold)

[[41003 20172 13192 40511]
 [58057 51723 15813 60047]
 [29440 40912 28609 57100]
 [15751 51757 39228 44230]
 [40025 62548 29758 53413]
 [43730 59668 16444 27946]
 [45532 30926 57714 35204]
 [39959 32535 27433 25137]
 [34103 52510 59040 41878]
 [47053 63273 41799 45183]]

[[332  37 328  16]
 [331 224 279 231]
 [156 130 136  45]
 [ 86  64 328  18]
 [295  58  91  41]
 [323 124 312  30]
 [ 79 211  40 241]
 [297 168 119  37]
 [280 210 141 294]
 [170 328  98 181]]


In [ ]:
print(daily_sales.shape)
print(daily_sales.ndim)
print(daily_sales.size)
print(daily_sales.dtype)

print()

print(units_sold.shape)
print(units_sold.ndim)
print(units_sold.size)
print(units_sold.dtype)

In [4]:
targets = np.full((10, 4), 15000)
print(targets)
print(targets.shape)
print(targets.ndim)
print(targets.dtype)

[[15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]]
(10, 4)
2
int64


In [ ]:
spaced = np.linspace(daily_sales.min(), daily_sales.max(), 10)
print(spaced)

In [5]:
np.random.seed(7)
clothing = np.random.normal(9500, 1200, 10)
print(clothing)
print(clothing.mean())
print(daily_sales[:, 2].mean())

[11528.63084456  8940.87515535  9539.38419641  9989.0195396
  8553.29236565  9502.47868749  9498.93153697  7394.33083239
 10721.1896068  10220.5982191 ]
9588.87309843134
32903.0


In [6]:
electronics = daily_sales[:, 1]
print(electronics)
print(electronics.max())

[20172 51723 40912 51757 62548 59668 30926 32535 52510 63273]
63273


In [ ]:
last_3_food = daily_sales[-3:, 0]
print(last_3_food)
print(last_3_food.mean())

In [7]:
cheap_cols = np.arange(0, 4, 2)
print(cheap_cols)

subgrid = daily_sales[:5, cheap_cols]
print(subgrid)
print(subgrid.shape)

[0 2]
[[41003 13192]
 [58057 15813]
 [29440 28609]
 [15751 39228]
 [40025 29758]]
(5, 2)


In [ ]:
even_days = daily_sales[::2, :]
print(even_days)
print(even_days.sum(axis=0))

In [ ]:
sub = daily_sales[3:6, 1:3].copy()
sub += 500
print(sub)
print(daily_sales[3:6, 1:3])

In [ ]:
sales_with_vat = daily_sales * 1.16
print(sales_with_vat)

In [ ]:
revenue_per_unit = (daily_sales / units_sold).round(2)
print(revenue_per_unit)

avg_per_unit = revenue_per_unit.mean(axis=0)
print(avg_per_unit)
print(categories[avg_per_unit.argmax()])

In [5]:
diff = daily_sales - targets # Daily sales and targets have the same shape, so subtracting them is feasible
print(diff)

print()

below_target = (diff < 0).sum(axis=0)
print(below_target)
# order is Food, Electronics, Clothing, Furniture

[[26003  5172 -1808 25511]
 [43057 36723   813 45047]
 [14440 25912 13609 42100]
 [  751 36757 24228 29230]
 [25025 47548 14758 38413]
 [28730 44668  1444 12946]
 [30532 15926 42714 20204]
 [24959 17535 12433 10137]
 [19103 37510 44040 26878]
 [32053 48273 26799 30183]]

[0 0 1 0]


In [ ]:
log_sales = np.log(daily_sales)
print(log_sales)
print()
print(log_sales.mean())

# Log reduces the influence of outliers making the data to behave more like a normal distribution.

[[10.62140051  9.91205078  9.48736586 10.60932882]
 [10.96918057 10.85365784  9.66858767 11.00288287]
 [10.29010957 10.6191787  10.26147663 10.9525594 ]
 [ 9.66465913 10.85431497 10.57714606 10.69715857]
 [10.59725954 11.04368954 10.30085328 10.88580944]
 [10.68578964 10.99655114  9.70771595 10.23802936]
 [10.72617065 10.33935253 10.96325506 10.46891499]
 [10.59560921 10.39007171 10.21950195 10.13209614]
 [10.43714064 10.86875891 10.98597046 10.64251591]
 [10.7590299  11.05521398 10.64062769 10.71847619]]

10.535986543990209


In [11]:
weighted_sales = daily_sales * np.array([1.0, 0.9, 1.0, 0.95])
print(weighted_sales)

[[41003.   18154.8  13192.   38485.45]
 [58057.   46550.7  15813.   57044.65]
 [29440.   36820.8  28609.   54245.  ]
 [15751.   46581.3  39228.   42018.5 ]
 [40025.   56293.2  29758.   50742.35]
 [43730.   53701.2  16444.   26548.7 ]
 [45532.   27833.4  57714.   33443.8 ]
 [39959.   29281.5  27433.   23880.15]
 [34103.   47259.   59040.   39784.1 ]
 [47053.   56945.7  41799.   42923.85]]


In [12]:
category_avg = daily_sales.mean(axis=0)
print(category_avg)
print(categories[category_avg.argmax()])
print(category_avg[category_avg.argmax()])

[39465.3 46602.4 32903.  43064.9]
Electronics
46602.4


In [9]:
daily_totals = daily_sales.sum(axis=1)
print(daily_totals)
print(day_numbers[daily_totals.argmax()])
print(day_numbers[daily_totals.argmin()])

[114878 185640 156061 150966 185744 147788 169376 125064 187531 197308]
10
1


In [8]:
category_std = daily_sales.std(axis=0)
print(category_std)
print(categories[category_std.argmax()])

[10736.70091835 14018.41327112 15580.80098711 11036.3868766 ]
Clothing


In [ ]:
cum_electronics = daily_sales[:, 1].cumsum()
print(cum_electronics)

crossed = cum_electronics > 400000
print(day_numbers[crossed.argmax()])

In [ ]:
electronics_share = daily_sales[:, 1] / daily_sales.sum(axis=1) * 100
print(electronics_share.round(2))
print(electronics_share.mean())

## Second Part

In [ ]:
reshaped = daily_sales.reshape(5, 8)
print(reshaped)
print(reshaped.shape)

# It doesn't make sense as it it not copatible with my day/category structure.


[[41003 20172 13192 40511 58057 51723 15813 60047]
 [29440 40912 28609 57100 15751 51757 39228 44230]
 [40025 62548 29758 53413 43730 59668 16444 27946]
 [45532 30926 57714 35204 39959 32535 27433 25137]
 [34103 52510 59040 41878 47053 63273 41799 45183]]
(5, 8)


In [10]:
transposed = daily_sales.T
print(transposed.shape)

category_mean_transposed = transposed.mean(axis=1)
print(category_mean_transposed)

print(daily_sales.mean(axis=0))

(4, 10)
[39465.3 46602.4 32903.  43064.9]
[39465.3 46602.4 32903.  43064.9]


In [13]:
day_totals = daily_sales.sum(axis=1, keepdims=True)
print(day_totals.shape)

residuals = daily_sales - day_totals
print(residuals)

(10, 1)
[[ -73875  -94706 -101686  -74367]
 [-127583 -133917 -169827 -125593]
 [-126621 -115149 -127452  -98961]
 [-135215  -99209 -111738 -106736]
 [-145719 -123196 -155986 -132331]
 [-104058  -88120 -131344 -119842]
 [-123844 -138450 -111662 -134172]
 [ -85105  -92529  -97631  -99927]
 [-153428 -135021 -128491 -145653]
 [-150255 -134035 -155509 -152125]]


In [ ]:
bonus_rates = np.array([0.05, 0.08, 0.06, 0.04])
bonus_amounts = daily_sales * bonus_rates
print(bonus_amounts)

In [ ]:
col_min = daily_sales.min(axis=0)
col_max = daily_sales.max(axis=0)

normalised = (daily_sales - col_min) / (col_max - col_min)
print(normalised)

In [ ]:
electronics = daily_sales[:, 1]
below_avg = electronics < electronics.mean()

print(electronics[below_avg])
print(below_avg.sum())

In [ ]:
food = daily_sales[:, 0]
clothing_sales = daily_sales[:, 2]

both_high = (food > 13000) & (clothing_sales > 9000)
print(daily_sales[both_high])

In [ ]:
high_units = units_sold > 200

print(units_sold[high_units])
print(high_units.sum())

In [ ]:
furniture = daily_sales[:, 3]
furniture_median = np.median(furniture)

above_median_mean = furniture[furniture > furniture_median].mean()
print(above_median_mean)
print(furniture.mean())

In [ ]:
daily_totals = daily_sales.sum(axis=1)
top_3_idx = np.argsort(daily_totals)[-3:]

print(day_numbers[top_3_idx])
print(daily_sales[top_3_idx])

In [ ]:
flag = np.where(daily_sales > 20000, 1, 0)
print(flag)
print(flag.sum())

In [ ]:
clothing_tier = np.where(clothing_sales > 10000, "Premium", np.where(clothing_sales >= 7500, "Standard", "Below Target"))

print(clothing_sales)
print(clothing_tier)

In [ ]:
electronics_mean = electronics.mean()
adjusted_electronics = np.where(electronics < 40000, electronics_mean, electronics)

print(adjusted_electronics)
print(electronics)

In [ ]:
flat_sorted = np.sort(daily_sales, axis=None)
top_5_values = flat_sorted[-5:]
print(top_5_values)

rows, cols = np.where(daily_sales >= top_5_values.min())
print(rows)
print(cols)

In [ ]:
bonus_sales = daily_sales * 1.0

bonus_sales[:, 0] = np.where(food > 13000, food * 1.05, food)
bonus_sales[:, 1] = np.where(electronics > 48000, electronics * 1.03, electronics)

print(bonus_sales)
print(daily_sales)

## NaN section and the rest of numpy assignment

In [15]:
daily_sales_float = daily_sales.astype(float)

daily_sales_float[2, 1] = np.nan
daily_sales_float[5, 3] = np.nan
daily_sales_float[8, 0] = np.nan

print(daily_sales_float)

[[41003. 20172. 13192. 40511.]
 [58057. 51723. 15813. 60047.]
 [29440.    nan 28609. 57100.]
 [15751. 51757. 39228. 44230.]
 [40025. 62548. 29758. 53413.]
 [43730. 59668. 16444.    nan]
 [45532. 30926. 57714. 35204.]
 [39959. 32535. 27433. 25137.]
 [   nan 52510. 59040. 41878.]
 [47053. 63273. 41799. 45183.]]


In [16]:
missing = np.isnan(daily_sales_float)

print(missing)
print(missing.sum())
print(missing.sum(axis=0))

[[False False False False]
 [False False False False]
 [False  True False False]
 [False False False False]
 [False False False False]
 [False False False  True]
 [False False False False]
 [False False False False]
 [ True False False False]
 [False False False False]]
3
[1 1 0 1]


In [ ]:
nan_means = np.nanmean(daily_sales_float, axis=0)
print(nan_means)

regular_means = daily_sales_float.mean(axis=0)
print(regular_means)

In [ ]:
col_medians = np.nanmedian(daily_sales_float, axis=0)
print(col_medians)

filled = daily_sales_float.copy()
row_idx, col_idx = np.where(np.isnan(filled))
filled[row_idx, col_idx] = col_medians[col_idx]

print(filled)
print(np.isnan(filled).sum())

In [ ]:
def clean_array(arr, sentinel=-1):
    arr = arr.astype(float)
    arr = np.where(arr == sentinel, np.nan, arr)

    col_means = np.nanmean(arr, axis=0)
    row_idx, col_idx = np.where(np.isnan(arr))
    arr[row_idx, col_idx] = col_means[col_idx]

    return arr

test_array = np.array([[12000, -1, 8000], [11000, 9500, -1], [-1, 10500, 7800]])
print(clean_array(test_array))