In [1]:
import numpy as np
print("ready")

ready


In [2]:
np.random.seed(1)

categories = ["Food", "Electronics", "Clothing", "Furniture"]
day_numbers = np.arange(1, 11)

daily_sales = np.random.randint(8000, 65000, size=(10, 4))
units_sold = np.random.randint(15, 350, size=(10, 4))

print(daily_sales)
print(units_sold)

[[41003 20172 13192 40511]
 [58057 51723 15813 60047]
 [29440 40912 28609 57100]
 [15751 51757 39228 44230]
 [40025 62548 29758 53413]
 [43730 59668 16444 27946]
 [45532 30926 57714 35204]
 [39959 32535 27433 25137]
 [34103 52510 59040 41878]
 [47053 63273 41799 45183]]
[[332  37 328  16]
 [331 224 279 231]
 [156 130 136  45]
 [ 86  64 328  18]
 [295  58  91  41]
 [323 124 312  30]
 [ 79 211  40 241]
 [297 168 119  37]
 [280 210 141 294]
 [170 328  98 181]]


### Shape, ndim, size, dtype

In [3]:
print(daily_sales.shape)
print(daily_sales.ndim)
print(daily_sales.size)
print(daily_sales.dtype)

print(units_sold.shape)
print(units_sold.ndim)
print(units_sold.size)
print(units_sold.dtype)

(10, 4)
2
40
int32
(10, 4)
2
40
int32


### np.full — targets array

In [4]:
targets = np.full((10, 4), 15000)
print(targets)
print(targets.shape)
print(targets.ndim)
print(targets.dtype)

[[15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]]
(10, 4)
2
int64


`np.full(shape, value)` fills every cell in the given shape with that one value — useful here as a constant baseline to compare `daily_sales` against.

### np.linspace across the daily_sales range

In [5]:
spaced = np.linspace(daily_sales.min(), daily_sales.max(), 10)
print(spaced)

[13192.         18756.55555556 24321.11111111 29885.66666667
 35450.22222222 41014.77777778 46579.33333333 52143.88888889
 57708.44444444 63273.        ]


### Simulated Clothing sales vs the real mean

In [6]:
np.random.seed(7)
simulated_clothing = np.random.normal(9500, 1200, 10)
print(simulated_clothing)
print(simulated_clothing.mean())
print(daily_sales[:, 2].mean())

[11528.63084456  8940.87515535  9539.38419641  9989.0195396
  8553.29236565  9502.47868749  9498.93153697  7394.33083239
 10721.1896068  10220.5982191 ]
9588.87309843134
32903.0


### Electronics column

In [7]:
electronics = daily_sales[:, 1]
print(electronics)
print(electronics.max())

[20172 51723 40912 51757 62548 59668 30926 32535 52510 63273]
63273


### Last 3 days of Food

In [8]:
last_3_food = daily_sales[-3:, 0]
print(last_3_food)
print(last_3_food.mean())

[39959 34103 47053]
40371.666666666664


### Subgrid — first 5 days, Food & Clothing (columns 0 and 2)

In [9]:
cheap_cols = np.arange(0, 4, 2)
print(cheap_cols)

subgrid = daily_sales[:5, cheap_cols]
print(subgrid)
print(subgrid.shape)

[0 2]
[[41003 13192]
 [58057 15813]
 [29440 28609]
 [15751 39228]
 [40025 29758]]
(5, 2)


### Every even-indexed day

In [10]:
even_days = daily_sales[::2, :]
print(even_days)
print(even_days.sum(axis=0))

[[41003 20172 13192 40511]
 [29440 40912 28609 57100]
 [40025 62548 29758 53413]
 [45532 30926 57714 35204]
 [34103 52510 59040 41878]]
[190103 207068 188313 228106]


### Hard: subgrid copy — confirm original is untouched

In [11]:
sub = daily_sales[3:6, 1:3].copy()
sub += 500
print(sub)
print(daily_sales[3:6, 1:3])

[[52257 39728]
 [63048 30258]
 [60168 16944]]
[[51757 39228]
 [62548 29758]
 [59668 16444]]


### 16% VAT

In [12]:
sales_with_vat = daily_sales * 1.16
print(sales_with_vat)

[[47563.48 23399.52 15302.72 46992.76]
 [67346.12 59998.68 18343.08 69654.52]
 [34150.4  47457.92 33186.44 66236.  ]
 [18271.16 60038.12 45504.48 51306.8 ]
 [46429.   72555.68 34519.28 61959.08]
 [50726.8  69214.88 19075.04 32417.36]
 [52817.12 35874.16 66948.24 40836.64]
 [46352.44 37740.6  31822.28 29158.92]
 [39559.48 60911.6  68486.4  48578.48]
 [54581.48 73396.68 48486.84 52412.28]]


### Revenue per unit sold

In [13]:
revenue_per_unit = (daily_sales / units_sold).round(2)
print(revenue_per_unit)

avg_per_unit = revenue_per_unit.mean(axis=0)
print(avg_per_unit)
print(categories[avg_per_unit.argmax()])

[[ 123.5   545.19   40.22 2531.94]
 [ 175.4   230.91   56.68  259.94]
 [ 188.72  314.71  210.36 1268.89]
 [ 183.15  808.7   119.6  2457.22]
 [ 135.68 1078.41  327.01 1302.76]
 [ 135.39  481.19   52.71  931.53]
 [ 576.35  146.57 1442.85  146.07]
 [ 134.54  193.66  230.53  679.38]
 [ 121.8   250.05  418.72  142.44]
 [ 276.78  192.91  426.52  249.63]]
[205.131 424.23  332.52  996.98 ]
Furniture


### Comparison against the KES 15,000 target

In [14]:
diff = daily_sales - 15000
print(diff)

below_target = (diff < 0).sum(axis=0)
print(below_target)
# order is Food, Electronics, Clothing, Furniture

[[26003  5172 -1808 25511]
 [43057 36723   813 45047]
 [14440 25912 13609 42100]
 [  751 36757 24228 29230]
 [25025 47548 14758 38413]
 [28730 44668  1444 12946]
 [30532 15926 42714 20204]
 [24959 17535 12433 10137]
 [19103 37510 44040 26878]
 [32053 48273 26799 30183]]
[0 0 1 0]


### Log transform

In [15]:
log_sales = np.log(daily_sales)
print(log_sales)
print(log_sales.mean())

[[10.62140051  9.91205078  9.48736586 10.60932882]
 [10.96918057 10.85365784  9.66858767 11.00288287]
 [10.29010957 10.6191787  10.26147663 10.9525594 ]
 [ 9.66465913 10.85431497 10.57714606 10.69715857]
 [10.59725954 11.04368954 10.30085328 10.88580944]
 [10.68578964 10.99655114  9.70771595 10.23802936]
 [10.72617065 10.33935253 10.96325506 10.46891499]
 [10.59560921 10.39007171 10.21950195 10.13209614]
 [10.43714064 10.86875891 10.98597046 10.64251591]
 [10.7590299  11.05521398 10.64062769 10.71847619]]
10.535986543990209


Log transform pulls big values in and spreads small ones out, so a handful of huge sales days pull the average around less than they would in raw terms — useful because sales data is usually skewed rather than symmetric.

### Hard: weighted_sales (single vectorized op)

In [16]:
weighted_sales = daily_sales * np.array([1.0, 0.9, 1.0, 0.95])
print(weighted_sales)

[[41003.   18154.8  13192.   38485.45]
 [58057.   46550.7  15813.   57044.65]
 [29440.   36820.8  28609.   54245.  ]
 [15751.   46581.3  39228.   42018.5 ]
 [40025.   56293.2  29758.   50742.35]
 [43730.   53701.2  16444.   26548.7 ]
 [45532.   27833.4  57714.   33443.8 ]
 [39959.   29281.5  27433.   23880.15]
 [34103.   47259.   59040.   39784.1 ]
 [47053.   56945.7  41799.   42923.85]]


### Category with the highest average

In [17]:
category_avg = daily_sales.mean(axis=0)
print(category_avg)
print(categories[category_avg.argmax()])
print(category_avg[category_avg.argmax()])

[39465.3 46602.4 32903.  43064.9]
Electronics
46602.4


### Total revenue per day

In [18]:
daily_totals = daily_sales.sum(axis=1)
print(daily_totals)
print(day_numbers[daily_totals.argmax()])
print(day_numbers[daily_totals.argmin()])

[114878 185640 156061 150966 185744 147788 169376 125064 187531 197308]
10
1


### Standard deviation per category

In [19]:
category_std = daily_sales.std(axis=0)
print(category_std)
print(categories[category_std.argmax()])

[10736.70091835 14018.41327112 15580.80098711 11036.3868766 ]
Clothing


### Cumulative Electronics revenue

In [20]:
cum_electronics = daily_sales[:, 1].cumsum()
print(cum_electronics)

crossed = cum_electronics > 400000
print(day_numbers[crossed.argmax()])

[ 20172  71895 112807 164564 227112 286780 317706 350241 402751 466024]
9


### Hard: Electronics' share of daily revenue

In [21]:
electronics_share = daily_sales[:, 1] / daily_sales.sum(axis=1) * 100
print(electronics_share.round(2))
print(electronics_share.mean())

[17.56 27.86 26.22 34.28 33.67 40.37 18.26 26.01 28.   32.07]
28.431141789123366
