In [ ]:
import numpy as np
fare = np.array([50,70,100,150,200 ])
print(fare)


In [ ]:
# 2 dimensional array
day_fares = np.array([[50, 70, 100],
                       [60, 80, 120],
                       [55, 75,110]])

print(day_fares)
print(day_fares.shape)


In [ ]:
np.zeros(5)
np.ones(5)
np.ones((2,3))
np.full((5, 2), 7.5)

In [ ]:
# Ranges
np.arange(0,10,2)

arange is for when you know the step size: linespace is for when you know how many want and want them spaced evenly apart.

#### Identity matrices

In [ ]:
np.eye(5)

In [8]:
# np.random.randint()
# Generates random integers/numbers within a range

# Simulate one wheel of random daily customers counts()
import numpy as np
np.random.seed(0) # for reproducibility
customers_counts = np.random.randint(50, 101, size=7)
print(customers_counts)

# 10 by 4 grid of random sales figure between 5000 and 60000
mock_sales = np.random.randint(5000, 60001, size=(10, 4))
print(mock_sales)

[94 97 50 53 53 89 59]
[[25757 51884 19935 20430]
 [53600 44512 57620 19650]
 [22089 37230 23983 48095]
 [56374 29152 40665 21921]
 [32469 43984 11921 43804]
 [ 7163 10072 42619 12877]
 [23430  6871 12599  7496]
 [52954 29675 47968 36921]
 [38523  5797 54811  8219]
 [20246 29999 21321 57489]]


In [ ]:
# np.random.normal()
# Generates random numbers from a normal (Gaussian) distribution.
# Generates numbers clustered around a mean, with the most values close and fewer far away
# This is how most real world quantities are distributed
np.random.seed(42)
normal_data = np.random.normal(100, 15, 1000)  # mean=100, std=15 size=1000
print(normal_data)

print()

food_sales_sim = np.random.normal(loc =13000, scale=15000, size=1000)
print(food_sales_sim.round(0))

print()

# Simulate Electronics: higher mean, more volatile (wider spread)
electronics_sim = np.random.normal(loc =45700, scale=5000, size=10)
print(electronics_sim.round(0))




### Understanding Array Properties

In [10]:
# .shape
# Returns a tuple telling the size of each dimension of the array.
# Tells us the rows and columns of the array
print(mock_sales.shape)
print(f"Days:{mock_sales.shape[0]}") # rows
print(f"Products:{mock_sales.shape[1]}") # columns

(10, 4)
Days:10
Products:4


In [12]:
# .ndim
# Tells the number of dimensions of the array
# 1 for a simple list of numbers
# 2 for a 2D array (matrix)
# 3 for a 3D array (cube)
print(mock_sales.ndim)
prices = np.array([10, 20, 30, 40, 50])
print(prices.ndim)

# 3D - imagine 5 week of data, each week has 10 days and 4 categories
five_weeks = np.array([5, 10, 4])
print(five_weeks.ndim)
print(five_weeks.shape)
print(five_weeks)

2
1
1
(3,)
[ 5 10  4]


In [ ]:
# .size
# Returns the number of elements in the array.
print(mock_sales.size)
print(mock_sales.shape)
print(mock_sales.shape[0] * mock_sales.shape[1])



40


### Indexing and slicing
- Indexing means grabbing a single element
- Slicing means grabbing a range of elements

#### 1D Indexing and Slicing

In [20]:
# Here, we give one index in the square brackets and it will return the value at that index.
average_daily_sales = np.mean(mock_sales, axis=0)
print(average_daily_sales)

# Access by position
print(average_daily_sales[0]) # first column
print(average_daily_sales[-1]) # last column
print(average_daily_sales[1:3]) # second and third columns

# Slicing: Syntax: array[start:end:step]
# Stop is exclusive - the element at the stop index is not included in the slice
# Step is optional - if not specified, it will default to 1
print(average_daily_sales[:2]) # first two columns
print(average_daily_sales[::2]) # every other column
print(average_daily_sales[::-1]) # reversed

[33260.5 28917.6 33344.2 27690.2]
33260.5
27690.2
[28917.6 33344.2]
[33260.5 28917.6]
[33260.5 33344.2]
[27690.2 33344.2 28917.6 33260.5]


### 2D Indexing and  Slicing
- Here we need two indices: [row, column]. The comma separates them.
- A colon by itself means all of them

In [ ]:
# Single element: Daily average sales [row, column]
print(mock_sales[0,0]) # first row, first column
print(mock_sales[0,1]) # first row, second column
print(mock_sales[1,0]) # second row, first column
print(mock_sales[-1,-1]) # last row, last column

# Entire row: Daily average sales for each day [row]
print(mock_sales[0,:]) # first row, all columns

# Entire column: Daily average sales for each day [column]
print(mock_sales[:,0]) # all rows, first column

# Subgrid: first 3 days, first 2 products [row, column]
print(mock_sales[:3,0:2]) # first 3 rows, first 2 columns

# Last 3 days, last 2 products [row, column]
print(mock_sales[-3:,-2:]) # last 3 rows, last 2 columns

# Other entire days, first 2 products [row, column]
alternate_days_sales = mock_sales[::2,:] # every other row, all columns
print(alternate_days_sales)
print(alternate_days_sales.shape)


# N/B A MEMORY WARNING:
# Slices are views not copies. If you modify a slice, you modify the original array.
# If you want to create a copy of the slice use the:
# copy() method. if  you want an independent copy
# subgrid_copy = daily_sales[:3,:].copy()
view = mock_sales[:2,:] 
view[0,0] = 9999
print(mock_sales[0,0]) # This will show 9999, indicating that the original array was not modified

# Safer version
mock_sales[0,0] = 5000 # Resetting the value back to the original for demonstration purposes
safe_copy = mock_sales[:2,:].copy() 
safe_copy[0,0] = 9999
print(mock_sales[0,0]) # This will show 5000, indicating the original array was modified


25757
51884
53600
57489
[25757 51884 19935 20430]
[25757 53600 22089 56374 32469  7163 23430 52954 38523 20246]


### Vectorised operations

In [ ]:
# Elementwise operations
# These operations are performed on each element of the array index by index.
# 1. Scalar operations: add, subtract, multiply, divide, and power
# Apply 16% VAT on products
products_with_vat = mock_sales * 1.16
print(products_with_vat)
# Subtract a fixed overhead of 1000 KES per product
net_profit = mock_sales - 1000
print(net_profit[0])




[[29878.12 60185.44 23124.6  23698.8 ]
 [62176.   51633.92 66839.2  22794.  ]
 [25623.24 43186.8  27820.28 55790.2 ]
 [65393.84 33816.32 47171.4  25428.36]
 [37664.04 51021.44 13828.36 50812.64]
 [ 8309.08 11683.52 49438.04 14937.32]
 [27178.8   7970.36 14614.84  8695.36]
 [61426.64 34423.   55642.88 42828.36]
 [44686.68  6724.52 63580.76  9534.04]
 [23485.36 34798.84 24732.36 66687.24]]
[[24757 50884 18935 19430]
 [52600 43512 56620 18650]
 [21089 36230 22983 47095]
 [55374 28152 39665 20921]
 [31469 42984 10921 42804]
 [ 6163  9072 41619 11877]
 [22430  5871 11599  6496]
 [51954 28675 46968 35921]
 [37523  4797 53811  7219]
 [19246 28999 20321 56489]]


In [27]:
# Array + Array = same shape
# Ttl revenue combining sales of all products for each day
online = mock_sales * 0.4
offline = mock_sales * 0.6
total_revenue = online + offline

print(online)
print("-"*10)
print(offline)
print("-"*10)
print(total_revenue)
print("-"*10)

[[10302.8 20753.6  7974.   8172. ]
 [21440.  17804.8 23048.   7860. ]
 [ 8835.6 14892.   9593.2 19238. ]
 [22549.6 11660.8 16266.   8768.4]
 [12987.6 17593.6  4768.4 17521.6]
 [ 2865.2  4028.8 17047.6  5150.8]
 [ 9372.   2748.4  5039.6  2998.4]
 [21181.6 11870.  19187.2 14768.4]
 [15409.2  2318.8 21924.4  3287.6]
 [ 8098.4 11999.6  8528.4 22995.6]]
----------
[[15454.2 31130.4 11961.  12258. ]
 [32160.  26707.2 34572.  11790. ]
 [13253.4 22338.  14389.8 28857. ]
 [33824.4 17491.2 24399.  13152.6]
 [19481.4 26390.4  7152.6 26282.4]
 [ 4297.8  6043.2 25571.4  7726.2]
 [14058.   4122.6  7559.4  4497.6]
 [31772.4 17805.  28780.8 22152.6]
 [23113.8  3478.2 32886.6  4931.4]
 [12147.6 17999.4 12792.6 34493.4]]
----------
[[25757. 51884. 19935. 20430.]
 [53600. 44512. 57620. 19650.]
 [22089. 37230. 23983. 48095.]
 [56374. 29152. 40665. 21921.]
 [32469. 43984. 11921. 43804.]
 [ 7163. 10072. 42619. 12877.]
 [23430.  6871. 12599.  7496.]
 [52954. 29675. 47968. 36921.]
 [38523.  5797. 54811.  8219

In [ ]:
# Universal functions (unfuncs)
# These are numpy functions that operate elementwise on array
# They are optimizedfor performance and can handle large datasets
# Some unfuncs include: 
# np.add(), np.subtract(), np.multiply(), np.divide(), np.sqrt(), np.exp()
daily_sales = np.random.randint(loc=13500, scale=1000, size=(10,7))